### ISSUE TITLE
Pinned entries do not persist after reboot 

### ISSUE THREAD

**Issue by GondekNP** [ryonakano/pinit#113] opened 2024-01-03 17:15 UTC
### Behavior

`Pin It!` works great as expected after install from PopShop, and launcher entries are added as expected.

However, the pinned entries are lost after reboot. To restore them, I need to return to `Pin It!` and re-open/re-save the entries for them to reappear. 

### System info:

Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy

**Comment by ryonakano** [comment] 2024-01-04 23:55
Confirmed on Pop!_OS 22.04 LTS, but not on Ubuntu 22.04 LTS which it is based on. Might be an issue of [Cosmic](https://github.com/pop-os/cosmic) but needs investigation.

**Comment by seathasky** [comment] 2024-01-24 12:18
Can confirm having this issue as well. Great piece of software otherwise.

**Comment by ryonakano** [comment] 2024-01-25 11:23
@seathasky Are you on Pop!_OS 22.04 LTS too?

**Comment by seathasky** [comment] 2024-01-25 13:16
> @seathasky Are you on Pop!_OS 22.04 LTS too?

Yep!

**Comment by seathasky** [comment] 2024-01-25 13:17
> @seathasky Are you on Pop!_OS 22.04 LTS too?
![Screenshot from 2024-01-25 08-16-55](https://github.com/ryonakano/pinit/assets/17598024/70d82eb7-7238-4362-a33b-ca360e7d16e3)
Yep!

**Comment by seathasky** [comment] 2024-01-25 13:21
I also have am odd issue where some of the icons are not there, but that's been a thing since I installed Pin It. I'm scared to remove them.

![image](https://github.com/ryonakano/pinit/assets/17598024/8677c251-c8c5-431c-9d8a-a2b1af9a2c39)

**Comment by ryonakano** [comment] 2024-01-25 13:58
> I also have am odd issue where some of the icons are not there, but that's been a thing since I installed Pin It. I'm scared to remove them.

Maybe that would be an issue I fixed in #109, which is not released yet… :see_no_evil:

**Comment by pterodyne** [comment] 2024-01-25 16:33
Same issue here, Debian 12 X86_64

**Closed** 2024-01-26 12:20 UTC
Labels: Priority: High, Status: Confirmed

**Comment by ryonakano** [comment] 2024-01-27 06:07
I've just released 2.0.3 with a fix for this issue. After updating to 2.0.3, please open Pin It! and choose the executable file and the icon file and press "Save" button for each app entry. After that, this issue should no longer happens even after reboot.
